# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtCoreSwitch.ui'
#
# Created: Thu Jan 21 17:33:06 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CoreSwitch(object):
    def setupUi(self, CoreSwitch):
        CoreSwitch.setObjectName(_fromUtf8("CoreSwitch"))
        CoreSwitch.resize(190, 200)
        CoreSwitch.setMaximumSize(QtCore.QSize(190, 200))
        self.label = QtGui.QLabel(CoreSwitch)
        self.label.setGeometry(QtCore.QRect(23, 14, 41, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.cbChips = QtGui.QComboBox(CoreSwitch)
        self.cbChips.setGeometry(QtCore.QRect(70, 10, 101, 31))
        self.cbChips.setObjectName(_fromUtf8("cbChips"))
        self.frame = QtGui.QFrame(CoreSwitch)
        self.frame.setGeometry(QtCore.QRect(10, 50, 171, 141))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.c0 = QtGui.QPushButton(self.frame)
        self.c0.setGeometry(QtCore.QRect(10, 10, 31, 29))
        self.c0.setCheckable(False)
        self.c0.setChecked(False)
        self.c0.setFlat(False)
        self.c0.setObjectName(_fromUtf8("c0"))
        self.c1 = QtGui.QPushButton(self.frame)
        self.c1.setGeometry(QtCore.QRect(40, 10, 31, 29))
        self.c1.setCheckable(True)
        self.c1.setChecked(False)
        self.c1.setFlat(False)
        self.c1.setObjectName(_fromUtf8("c1"))
        self.c2 = QtGui.QPushButton(self.frame)
        self.c2.setGeometry(QtCore.QRect(70, 10, 31, 29))
        self.c2.setCheckable(True)
        self.c2.setChecked(False)
        self.c2.setFlat(False)
        self.c2.setObjectName(_fromUtf8("c2"))
        self.c3 = QtGui.QPushButton(self.frame)
        self.c3.setGeometry(QtCore.QRect(100, 10, 31, 29))
        self.c3.setCheckable(True)
        self.c3.setChecked(False)
        self.c3.setFlat(False)
        self.c3.setObjectName(_fromUtf8("c3"))
        self.c4 = QtGui.QPushButton(self.frame)
        self.c4.setGeometry(QtCore.QRect(130, 10, 31, 29))
        self.c4.setCheckable(True)
        self.c4.setChecked(False)
        self.c4.setFlat(False)
        self.c4.setObjectName(_fromUtf8("c4"))
        self.c5 = QtGui.QPushButton(self.frame)
        self.c5.setGeometry(QtCore.QRect(10, 40, 31, 29))
        self.c5.setCheckable(True)
        self.c5.setChecked(False)
        self.c5.setFlat(False)
        self.c5.setObjectName(_fromUtf8("c5"))
        self.c6 = QtGui.QPushButton(self.frame)
        self.c6.setGeometry(QtCore.QRect(40, 40, 31, 29))
        self.c6.setCheckable(True)
        self.c6.setChecked(False)
        self.c6.setFlat(False)
        self.c6.setObjectName(_fromUtf8("c6"))
        self.c7 = QtGui.QPushButton(self.frame)
        self.c7.setGeometry(QtCore.QRect(70, 40, 31, 29))
        self.c7.setCheckable(True)
        self.c7.setChecked(False)
        self.c7.setFlat(False)
        self.c7.setObjectName(_fromUtf8("c7"))
        self.c8 = QtGui.QPushButton(self.frame)
        self.c8.setGeometry(QtCore.QRect(100, 40, 31, 29))
        self.c8.setCheckable(True)
        self.c8.setChecked(False)
        self.c8.setFlat(False)
        self.c8.setObjectName(_fromUtf8("c8"))
        self.c9 = QtGui.QPushButton(self.frame)
        self.c9.setGeometry(QtCore.QRect(130, 40, 31, 29))
        self.c9.setCheckable(True)
        self.c9.setChecked(False)
        self.c9.setFlat(False)
        self.c9.setObjectName(_fromUtf8("c9"))
        self.c10 = QtGui.QPushButton(self.frame)
        self.c10.setGeometry(QtCore.QRect(10, 70, 31, 29))
        self.c10.setCheckable(True)
        self.c10.setChecked(False)
        self.c10.setFlat(False)
        self.c10.setObjectName(_fromUtf8("c10"))
        self.c11 = QtGui.QPushButton(self.frame)
        self.c11.setGeometry(QtCore.QRect(40, 70, 31, 29))
        self.c11.setCheckable(True)
        self.c11.setChecked(False)
        self.c11.setFlat(False)
        self.c11.setObjectName(_fromUtf8("c11"))
        self.c12 = QtGui.QPushButton(self.frame)
        self.c12.setGeometry(QtCore.QRect(70, 70, 31, 29))
        self.c12.setCheckable(True)
        self.c12.setChecked(False)
        self.c12.setFlat(False)
        self.c12.setObjectName(_fromUtf8("c12"))
        self.c13 = QtGui.QPushButton(self.frame)
        self.c13.setGeometry(QtCore.QRect(100, 70, 31, 29))
        self.c13.setCheckable(True)
        self.c13.setChecked(False)
        self.c13.setFlat(False)
        self.c13.setObjectName(_fromUtf8("c13"))
        self.c14 = QtGui.QPushButton(self.frame)
        self.c14.setGeometry(QtCore.QRect(130, 70, 31, 29))
        self.c14.setCheckable(True)
        self.c14.setChecked(False)
        self.c14.setFlat(False)
        self.c14.setObjectName(_fromUtf8("c14"))
        self.c15 = QtGui.QPushButton(self.frame)
        self.c15.setGeometry(QtCore.QRect(10, 100, 31, 29))
        self.c15.setCheckable(True)
        self.c15.setChecked(False)
        self.c15.setFlat(False)
        self.c15.setObjectName(_fromUtf8("c15"))
        self.c16 = QtGui.QPushButton(self.frame)
        self.c16.setGeometry(QtCore.QRect(40, 100, 31, 29))
        self.c16.setCheckable(True)
        self.c16.setChecked(False)
        self.c16.setFlat(False)
        self.c16.setObjectName(_fromUtf8("c16"))
        self.c17 = QtGui.QPushButton(self.frame)
        self.c17.setGeometry(QtCore.QRect(70, 100, 31, 29))
        self.c17.setCheckable(True)
        self.c17.setChecked(False)
        self.c17.setFlat(False)
        self.c17.setObjectName(_fromUtf8("c17"))

        self.retranslateUi(CoreSwitch)
        QtCore.QMetaObject.connectSlotsByName(CoreSwitch)

    def retranslateUi(self, CoreSwitch):
        CoreSwitch.setWindowTitle(_translate("CoreSwitch", "Toggle Core", None))
        self.label.setText(_translate("CoreSwitch", "Chip:", None))
        self.c0.setText(_translate("CoreSwitch", "0", None))
        self.c1.setText(_translate("CoreSwitch", "1", None))
        self.c2.setText(_translate("CoreSwitch", "2", None))
        self.c3.setText(_translate("CoreSwitch", "3", None))
        self.c4.setText(_translate("CoreSwitch", "4", None))
        self.c5.setText(_translate("CoreSwitch", "5", None))
        self.c6.setText(_translate("CoreSwitch", "6", None))
        self.c7.setText(_translate("CoreSwitch", "7", None))
        self.c8.setText(_translate("CoreSwitch", "8", None))
        self.c9.setText(_translate("CoreSwitch", "9", None))
        self.c10.setText(_translate("CoreSwitch", "10", None))
        self.c11.setText(_translate("CoreSwitch", "11", None))
        self.c12.setText(_translate("CoreSwitch", "12", None))
        self.c13.setText(_translate("CoreSwitch", "13", None))
        self.c14.setText(_translate("CoreSwitch", "14", None))
        self.c15.setText(_translate("CoreSwitch", "15", None))
        self.c16.setText(_translate("CoreSwitch", "16", None))
        self.c17.setText(_translate("CoreSwitch", "17", None))

